### ISSUE TITLE
unarg_samples/draw_subpasses failing to compile

### ISSUE THREAD

**Issue by dolanor** [vkngwrapper/examples#1]
Hi!
I tried to run it on my machine (ubuntu 20.04) but it failed.
```
~/go/src/github.com/vkngwrapper/examples/lunarg_samples/draw_subpasses$ go run .
# github.com/vkngwrapper/core/core1_0
/home/dolanor/go/pkg/mod/github.com/vkngwrapper/core@v1.0.1/core1_0/pipeline_createinfo.go:105:49: cannot convert (_Ciconst_VK_NULL_HANDLE) (untyped int constant 0) to type _Ctype_VkPipeline
```

**Comment by CannibalVox** [comment]
It looks like all samples will fail because this is a compiler error in vkngwrapper/core - unfortunately, it does build on my machine (windows) so this is probably not going to be an easy fix.

`createInfo.basePipelineHandle = (C.VkPipeline)(C.VK_NULL_HANDLE)` - this is the line

VK_NULL_HANDLE is a const that exists to be specifically used for that purpose. I can't get to my mac right now to see if I can repro it on that- could you do me a favor and:

A) Verify that `go build ./...` fails for vkngwrapper/core on your machine
B) See if changing that line to `createInfo.basePipelineHandle = (C.VkPipeline)(nil)` fixes it?

**Comment by CannibalVox** [comment]
What arch is your computer, and is it 64-bit? I wonder if this is due to differences in VK_NULL_HANDLE definitions for 32-bit

**Comment by CannibalVox** [comment]
We spoke offline- this issue has been addressed.  There were also issues with users not being directed to install the Vulkan SDK when onboarding via some paths (for instance, examples repo instead of vulkan-tutorial). That has also been addressed.

The last remaining issue coming up from our conversation is that the LunarG validation messages are CONSIDERABLY noisier than the vulkan-tutorial validation messages. I need to address that.

**Comment by CannibalVox** [comment]
That's been addressed & I think this is good to close now.
